apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::794496069247:role/UdacityFlaskDeployCBKubectlRole
      username: build  
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::794496069247:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-ZSWDLFYJD9OT
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2021-08-31T15:21:59Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1268"
  uid: 2f35b8a6-9920-4215-9135-4d9bd9b56927
